# সরকারি কর্মকর্তাদের বেতন বিশ্লেষণ — Pandas পূর্ণাঙ্গ Notebook

**শেখার বিষয়:** DataFrame তৈরি, CSV পড়া/লেখা, filtering, groupby, pivot table, merge, এবং Excel export

**প্রেক্ষাপট:** একটি কাল্পনিক উপজেলার কর্মকর্তা-কর্মচারীদের বেতন ব্যবস্থাপনা

---
## ধাপ ১ — Library Import ও ডেটা তৈরি

In [1]:
import pandas as pd
import numpy as np

# DataFrame তৈরি — সরকারি কর্মকর্তা-কর্মচারীর ডেটা
data = {
    'আইডি':        ['UZ-001','UZ-002','UZ-003','UZ-004','UZ-005',
                    'UZ-006','UZ-007','UZ-008','UZ-009','UZ-010',
                    'UZ-011','UZ-012','UZ-013','UZ-014','UZ-015'],
    'নাম':         ['মো. আবদুল করিম','রহিমা বেগম','জাহিদ হোসেন','সালমা খাতুন','কামাল উদ্দিন',
                    'নাসরিন আক্তার','রফিকুল ইসলাম','ফারজানা ইসলাম','মোমেনা বেগম','আবুল হাসেম',
                    'শিরিন আক্তার','মোস্তফা কামাল','রেহানা পারভীন','আনিসুর রহমান','তাহমিনা বেগম'],
    'পদবি':        ['UNO','AC Land','ICT Officer','Health Officer','Agriculture Officer',
                    'Education Officer','Accounts Officer','Family Planning Officer','MLSS','MLSS',
                    'Office Assistant','Sub Assistant Engineer','Sub Assistant','Driver','Sweeper'],
    'বিভাগ':       ['প্রশাসন','রাজস্ব','ICT','স্বাস্থ্য','কৃষি',
                    'শিক্ষা','অর্থ','স্বাস্থ্য','প্রশাসন','প্রশাসন',
                    'প্রশাসন','প্রকৌশল','ICT','প্রশাসন','প্রশাসন'],
    'গ্রেড':        [3, 6, 9, 9, 10, 10, 11, 10, 20, 20, 16, 14, 16, 16, 20],
    'মূল_বেতন':    [78000,56500,43000,43000,35500,35500,29000,35500,8250,8250,
                    11000,16000,11000,11000,8250],
    'যোগদান_তারিখ':['2009-03-15','2014-06-01','2017-08-20','2015-11-10','2018-04-05',
                    '2016-07-22','2012-01-30','2017-09-14','2004-02-18','2006-05-25',
                    '2019-10-11','2013-03-08','2020-06-15','2011-12-01','2003-09-27'],
    'লিঙ্গ':        ['পুরুষ','মহিলা','পুরুষ','মহিলা','পুরুষ',
                    'মহিলা','পুরুষ','মহিলা','মহিলা','পুরুষ',
                    'মহিলা','পুরুষ','মহিলা','পুরুষ','মহিলা'],
    'শিক্ষাগত_যোগ্যতা':['স্নাতকোত্তর','স্নাতকোত্তর','স্নাতক (ইঞ্জি.)','MBBS','স্নাতক',
                        'স্নাতকোত্তর','স্নাতক','MBBS','এসএসসি','এসএসসি',
                        'এইচএসসি','ডিপ্লোমা','এইচএসসি','এসএসসি','অষ্টম শ্রেণি']
}

df = pd.DataFrame(data)

# তারিখ column টা সঠিক format-এ রূপান্তর
df['যোগদান_তারিখ'] = pd.to_datetime(df['যোগদান_তারিখ'])

print(f'DataFrame তৈরি সম্পন্ন। Shape: {df.shape} → ({df.shape[0]} জন কর্মকর্তা, {df.shape[1]}টি তথ্য)')
print(f'\nColumn তালিকা: {list(df.columns)}')

DataFrame তৈরি সম্পন্ন। Shape: (15, 9) → (15 জন কর্মকর্তা, 9টি তথ্য)

Column তালিকা: ['আইডি', 'নাম', 'পদবি', 'বিভাগ', 'গ্রেড', 'মূল_বেতন', 'যোগদান_তারিখ', 'লিঙ্গ', 'শিক্ষাগত_যোগ্যতা']

---
## ধাপ ২ — DataFrame প্রাথমিক পরিচিতি

In [2]:
# প্রথম ৫ সারি দেখা
print('=== প্রথম ৫ সারি (head) ===')
df.head()

=== প্রথম ৫ সারি (head) ===

,আইডি,নাম,পদবি,বিভাগ,গ্রেড,মূল_বেতন,যোগদান_তারিখ,লিঙ্গ,শিক্ষাগত_যোগ্যতা
0,UZ-001,মো. আবদুল করিম,UNO,প্রশাসন,3,78000,2009-03-15,পুরুষ,স্নাতকোত্তর
1,UZ-002,রহিমা বেগম,AC Land,রাজস্ব,6,56500,2014-06-01,মহিলা,স্নাতকোত্তর
2,UZ-003,জাহিদ হোসেন,ICT Officer,ICT,9,43000,2017-08-20,পুরুষ,স্নাতক (ইঞ্জি.)
3,UZ-004,সালমা খাতুন,Health Officer,স্বাস্থ্য,9,43000,2015-11-10,মহিলা,MBBS
4,UZ-005,কামাল উদ্দিন,Agriculture Officer,কৃষি,10,35500,2018-04-05,পুরুষ,স্নাতক

In [3]:
# সংখ্যামূলক column-এর statistics
print('=== সংখ্যামূলক তথ্যের সারসংক্ষেপ ===')
df[['গ্রেড','মূল_বেতন']].describe().round(0)

=== সংখ্যামূলক তথ্যের সারসংক্ষেপ ===

       গ্রেড  মূল_বেতন
count   15.0      15.0
mean    13.0   28650.0
std      5.0   20885.0
min      3.0    8250.0
25%     10.0   11000.0
50%     11.0   29000.0
75%     16.0   39250.0
max     20.0   78000.0

In [4]:
# DataFrame-এর গঠন
print('=== DataFrame এর গঠন (info) ===')
df.info()

=== DataFrame এর গঠন (info) ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   আইডি              15 non-null     object
 1   নাম               15 non-null     object
 2   পদবি              15 non-null     object
 3   বিভাগ             15 non-null     object
 4   গ্রেড             15 non-null     int64
 5   মূল_বেতন          15 non-null     int64
 6   যোগদান_তারিখ      15 non-null     datetime64[ns]
 7   লিঙ্গ             15 non-null     object
 8   শিক্ষাগত_যোগ্যতা  15 non-null     object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 1.2+ KB

---
## ধাপ ৩ — নতুন Column তৈরি (Derived Columns)

In [5]:
# বাড়িভাড়া ভাতা: মূল বেতনের ৪৫%
df['বাড়িভাড়া'] = (df['মূল_বেতন'] * 0.45).round(0).astype(int)

# চিকিৎসা ভাতা: সবার জন্য ১,৫০০ টাকা
df['চিকিৎসা_ভাতা'] = 1500

# মোট বেতন
df['মোট_বেতন'] = df['মূল_বেতন'] + df['বাড়িভাড়া'] + df['চিকিৎসা_ভাতা']

# চাকরির বয়স (বছরে)
আজকের_তারিখ = pd.Timestamp('2025-01-01')
df['চাকরির_বছর'] = ((আজকের_তারিখ - df['যোগদান_তারিখ']).dt.days / 365).round(1)

# বেতন স্তর নির্ধারণ
bins   = [0, 15000, 30000, 50000, 100000]
labels = ['নিম্ন (১৫ হাজারের নিচে)', 'মধ্যম (১৫-৩০ হাজার)',
          'উচ্চ-মধ্যম (৩০-৫০ হাজার)', 'উচ্চ (৫০ হাজারের উপরে)']
df['বেতন_স্তর'] = pd.cut(df['মূল_বেতন'], bins=bins, labels=labels)

print('নতুন column যোগ হয়েছে: বাড়িভাড়া, চিকিৎসা_ভাতা, মোট_বেতন, চাকরির_বছর, বেতন_স্তর')
df[['নাম','মূল_বেতন','বাড়িভাড়া','চিকিৎসা_ভাতা','মোট_বেতন','চাকরির_বছর']].head(5)

নতুন column যোগ হয়েছে: বাড়িভাড়া, চিকিৎসা_ভাতা, মোট_বেতন, চাকরির_বছর, বেতন_স্তর

              নাম  মূল_বেতন  বাড়িভাড়া  চিকিৎসা_ভাতা  মোট_বেতন  চাকরির_বছর
0  মো. আবদুল করিম     78000       35100          1500    114600        15.8
1      রহিমা বেগম     56500       25425          1500     83425        10.6
2     জাহিদ হোসেন     43000       19350          1500     63850         7.4
3     সালমা খাতুন     43000       19350          1500     63850         9.2
4    কামাল উদ্দিন     35500       15975          1500     52975         6.7

---
## ধাপ ৪ — CSV ফাইল সংরক্ষণ ও পুনরায় পড়া

In [6]:
# CSV-তে সংরক্ষণ
df.to_csv('বেতন_ডেটা.csv', index=False, encoding='utf-8-sig')
print('✓ বেতন_ডেটা.csv সংরক্ষিত হয়েছে')

# আবার পড়া
df_পড়া = pd.read_csv('বেতন_ডেটা.csv', encoding='utf-8-sig')
df_পড়া['যোগদান_তারিখ'] = pd.to_datetime(df_পড়া['যোগদান_তারিখ'])
print(f'✓ CSV পড়া সম্পন্ন। সারি: {len(df_পড়া)}, Column: {len(df_পড়া.columns)}')
print('\nCSV থেকে পড়া ডেটা:')
df_পড়া[['আইডি','নাম','পদবি','মোট_বেতন']].head()

✓ বেতন_ডেটা.csv সংরক্ষিত হয়েছে
✓ CSV পড়া সম্পন্ন। সারি: 15, Column: 14

CSV থেকে পড়া ডেটা:

     আইডি             নাম                 পদবি  মোট_বেতন
0  UZ-001  মো. আবদুল করিম                  UNO    114600
1  UZ-002      রহিমা বেগম              AC Land     83425
2  UZ-003     জাহিদ হোসেন          ICT Officer     63850
3  UZ-004     সালমা খাতুন       Health Officer     63850
4  UZ-005    কামাল উদ্দিন  Agriculture Officer     52975

---
## ধাপ ৫ — Filtering (শর্ত দিয়ে তথ্য খোঁজা)

In [7]:
# একটি শর্ত: মূল বেতন ৩০,০০০ টাকার বেশি
উচ্চ_বেতন = df[df['মূল_বেতন'] > 30000]
print(f'৩০,০০০+ বেতনধারী কর্মকর্তা: {len(উচ্চ_বেতন)} জন')
উচ্চ_বেতন[['নাম','পদবি','মূল_বেতন','মোট_বেতন']]

৩০,০০০+ বেতনধারী কর্মকর্তা: 7 জন

              নাম                     পদবি  মূল_বেতন  মোট_বেতন
0  মো. আবদুল করিম                      UNO     78000    114600
1      রহিমা বেগম                  AC Land     56500     83425
2     জাহিদ হোসেন              ICT Officer     43000     63850
3     সালমা খাতুন           Health Officer     43000     63850
4    কামাল উদ্দিন      Agriculture Officer     35500     52975
5   নাসরিন আক্তার        Education Officer     35500     52975
7   ফারজানা ইসলাম  Family Planning Officer     35500     52975

In [8]:
# একাধিক শর্ত: ICT বিভাগ AND মহিলা কর্মকর্তা
# | মানে OR, & মানে AND
ict_মহিলা = df[(df['বিভাগ'] == 'ICT') | (df['লিঙ্গ'] == 'মহিলা')]
print(f'ICT বিভাগ অথবা মহিলা কর্মকর্তা: {len(ict_মহিলা)} জন')
ict_মহিলা[['নাম','বিভাগ','লিঙ্গ','পদবি']]

ICT বিভাগ অথবা মহিলা কর্মকর্তা: 9 জন

              নাম      বিভাগ  লিঙ্গ                     পদবি
1      রহিমা বেগম     রাজস্ব  মহিলা                  AC Land
2     জাহিদ হোসেন        ICT  পুরুষ              ICT Officer
3     সালমা খাতুন  স্বাস্থ্য  মহিলা           Health Officer
5   নাসরিন আক্তার     শিক্ষা  মহিলা        Education Officer
7   ফারজানা ইসলাম  স্বাস্থ্য  মহিলা  Family Planning Officer
8     মোমেনা বেগম    প্রশাসন  মহিলা                     MLSS
10   শিরিন আক্তার    প্রশাসন  মহিলা         Office Assistant
12  রেহানা পারভীন        ICT  মহিলা            Sub Assistant
14   তাহমিনা বেগম    প্রশাসন  মহিলা                  Sweeper

In [24]:
# isin() — একাধিক মানের মধ্যে আছে কিনা
নির্দিষ্ট_বিভাগ = df[df['বিভাগ'].isin(['প্রশাসন', 'ICT', 'অর্থ'])]
print(f'প্রশাসন/ICT/অর্থ বিভাগের কর্মকর্তা: {len(নির্দিষ্ট_বিভাগ)} জন')

# query() পদ্ধতি — আরো পড়তে সহজ
সিনিয়র = df[(df['চাকরির_বছর'] >= 10) & (df['মূল_বেতন'] > 20000)]
print(f'১০+ বছর চাকরি ও ২০,০০০+ বেতন: {len(সিনিয়র)} জন')
সিনিয়র[['নাম','পদবি','চাকরির_বছর','মূল_বেতন']]

প্রশাসন/ICT/অর্থ বিভাগের কর্মকর্তা: 9 জন
১০+ বছর চাকরি ও ২০,০০০+ বেতন: 3 জন

              নাম              পদবি  চাকরির_বছর  মূল_বেতন
0  মো. আবদুল করিম               UNO        15.8     78000
1      রহিমা বেগম           AC Land        10.6     56500
6    রফিকুল ইসলাম  Accounts Officer        12.9     29000

---
## ধাপ ৬ — Sorting (ক্রমানুসারে সাজানো)

In [11]:
# বেতন অনুযায়ী বড় থেকে ছোট
print('=== বেতন অনুযায়ী তালিকা (বড় থেকে ছোট) ===')
df.sort_values('মূল_বেতন', ascending=False)[['নাম','পদবি','মূল_বেতন','মোট_বেতন']]

=== বেতন অনুযায়ী তালিকা (বড় থেকে ছোট) ===

               নাম                     পদবি  মূল_বেতন  মোট_বেতন
0   মো. আবদুল করিম                      UNO     78000    114600
1       রহিমা বেগম                  AC Land     56500     83425
2      জাহিদ হোসেন              ICT Officer     43000     63850
3      সালমা খাতুন           Health Officer     43000     63850
4     কামাল উদ্দিন      Agriculture Officer     35500     52975
5    নাসরিন আক্তার        Education Officer     35500     52975
7    ফারজানা ইসলাম  Family Planning Officer     35500     52975
6     রফিকুল ইসলাম         Accounts Officer     29000     43550
11   মোস্তফা কামাল   Sub Assistant Engineer     16000     24700
10    শিরিন আক্তার         Office Assistant     11000     17450
12   রেহানা পারভীন            Sub Assistant     11000     17450
13    আনিসুর রহমান                   Driver     11000     17450
8      মোমেনা বেগম                     MLSS      8250     13462
9       আবুল হাসেম                     MLSS      8250     13462
14    তাহমিনা বেগম                  Sweeper      8250     13462

In [ ]:
# একাধিক column দিয়ে sort: প্রথমে বিভাগ, তারপর বেতন
print('=== বিভাগ ও বেতন অনুযায়ী সাজানো ===')
df.sort_values(['বিভাগ','মূল_বেতন'], ascending=[True, False])[['বিভাগ','নাম','মূল_বেতন']]

---
## ধাপ ৭ — GroupBy (বিভাগ অনুযায়ী বিশ্লেষণ)

In [12]:
# বিভাগ অনুযায়ী গড় ও মোট বেতন
print('=== বিভাগভিত্তিক বেতন বিশ্লেষণ ===')
বিভাগ_বিশ্লেষণ = df.groupby('বিভাগ')['মূল_বেতন'].agg(
    কর্মকর্তা_সংখ্যা='count',
    মোট_বেতন='sum',
    গড়_বেতন='mean',
    সর্বোচ্চ='max',
    সর্বনিম্ন='min'
).round(0).sort_values('মোট_বেতন', ascending=False)

বিভাগ_বিশ্লেষণ

=== বিভাগভিত্তিক বেতন বিশ্লেষণ ===

           কর্মকর্তা_সংখ্যা  মোট_বেতন  গড়_বেতন  সর্বোচ্চ  সর্বনিম্ন
বিভাগ
প্রশাসন                   6    124750   20792.0     78000       8250
স্বাস্থ্য                 2     78500   39250.0     43000      35500
রাজস্ব                    1     56500   56500.0     56500      56500
ICT                       2     54000   27000.0     43000      11000
কৃষি                      1     35500   35500.0     35500      35500
শিক্ষা                    1     35500   35500.0     35500      35500
অর্থ                      1     29000   29000.0     29000      29000
প্রকৌশল                   1     16000   16000.0     16000      16000

In [13]:
# লিঙ্গভিত্তিক তুলনামূলক বিশ্লেষণ
print('=== লিঙ্গভিত্তিক বেতন তুলনা ===')
লিঙ্গ_বিশ্লেষণ = df.groupby('লিঙ্গ').agg(
    কর্মকর্তা_সংখ্যা=('নাম','count'),
    গড়_মূল_বেতন=('মূল_বেতন','mean'),
    গড়_মোট_বেতন=('মোট_বেতন','mean'),
    গড়_চাকরির_বছর=('চাকরির_বছর','mean')
).round(0)

লিঙ্গ_বিশ্লেষণ

=== লিঙ্গভিত্তিক বেতন তুলনা ===

       কর্মকর্তা_সংখ্যা  গড়_মূল_বেতন  গড়_মোট_বেতন  গড়_চাকরির_বছর
লিঙ্গ
পুরুষ                 7       31536.0       47227.0            12.0
মহিলা                 8       26125.0       39381.0            11.0

In [14]:
# বিভাগ ও লিঙ্গ — দুটো column দিয়ে groupby
print('=== বিভাগ ও লিঙ্গ অনুযায়ী বিশ্লেষণ ===')
df.groupby(['বিভাগ','লিঙ্গ'])['মূল_বেতন'].agg(['count','mean']).round(0)

=== বিভাগ ও লিঙ্গ অনুযায়ী বিশ্লেষণ ===

                 count     mean
বিভাগ     লিঙ্গ
ICT       পুরুষ      1  43000.0
          মহিলা      1  11000.0
অর্থ      পুরুষ      1  29000.0
কৃষি      পুরুষ      1  35500.0
প্রকৌশল   পুরুষ      1  16000.0
প্রশাসন   পুরুষ      3  32417.0
          মহিলা      3   9167.0
রাজস্ব    মহিলা      1  56500.0
শিক্ষা    মহিলা      1  35500.0
স্বাস্থ্য মহিলা      2  39250.0

---
## ধাপ ৮ — Pivot Table (সারসংক্ষেপ টেবিল)

In [15]:
# বিভাগ vs লিঙ্গ — গড় বেতনের pivot table
print('=== Pivot Table: বিভাগ ও লিঙ্গ অনুযায়ী গড় মূল বেতন ===')
pivot = pd.pivot_table(
    df,
    values='মূল_বেতন',
    index='বিভাগ',
    columns='লিঙ্গ',
    aggfunc='mean',
    fill_value=0,
    margins=True,           # সর্বমোট সারি ও column
    margins_name='সর্বমোট'
).round(0)

pivot

=== Pivot Table: বিভাগ ও লিঙ্গ অনুযায়ী গড় মূল বেতন ===

লিঙ্গ        পুরুষ    মহিলা  সর্বমোট
বিভাগ
ICT        43000.0  11000.0  27000.0
অর্থ       29000.0      0.0  29000.0
কৃষি       35500.0      0.0  35500.0
প্রকৌশল    16000.0      0.0  16000.0
প্রশাসন    32417.0   9167.0  20792.0
রাজস্ব         0.0  56500.0  56500.0
শিক্ষা         0.0  35500.0  35500.0
স্বাস্থ্য      0.0  39250.0  39250.0
সর্বমোট    31536.0  26125.0  28650.0

In [16]:
# বেতন স্তর vs বিভাগ — কর্মকর্তা সংখ্যার pivot
print('=== বেতন স্তর অনুযায়ী বিভাগভিত্তিক কর্মকর্তা সংখ্যা ===')
pd.pivot_table(
    df,
    values='নাম',
    index='বেতন_স্তর',
    columns='লিঙ্গ',
    aggfunc='count',
    fill_value=0,
    margins=True,
    margins_name='মোট'
)

=== বেতন স্তর অনুযায়ী বিভাগভিত্তিক কর্মকর্তা সংখ্যা ===

লিঙ্গ                     পুরুষ  মহিলা  মোট
বেতন_স্তর
নিম্ন (১৫ হাজারের নিচে)       2      4    6
মধ্যম (১৫-৩০ হাজার)           2      0    2
উচ্চ-মধ্যম (৩০-৫০ হাজার)      2      3    5
উচ্চ (৫০ হাজারের উপরে)        1      1    2
মোট                           7      8   15

---
## ধাপ ৯ — Apply ও Lambda (কাস্টম হিসাব)

In [17]:
# বার্ষিক ইনক্রিমেন্ট হিসাব (সরকারি নিয়ম অনুযায়ী)
def ইনক্রিমেন্ট_হিসাব(row):
    """গ্রেড অনুযায়ী ইনক্রিমেন্ট হার নির্ধারণ"""
    if row['গ্রেড'] <= 5:
        return round(row['মূল_বেতন'] * 0.05)   # ৫%
    elif row['গ্রেড'] <= 10:
        return round(row['মূল_বেতন'] * 0.05)   # ৫%
    else:
        return round(row['মূল_বেতন'] * 0.05)   # ৫%

df['বার্ষিক_ইনক্রিমেন্ট'] = df.apply(ইনক্রিমেন্ট_হিসাব, axis=1)
df['পরবর্তী_বছর_বেতন']    = df['মূল_বেতন'] + df['বার্ষিক_ইনক্রিমেন্ট']

# Lambda দিয়ে সংক্ষিপ্ত পদ্ধতি
df['৩_বছর_পরের_বেতন'] = df['মূল_বেতন'].apply(lambda x: round(x * 1.05**3))

print('=== বার্ষিক ইনক্রিমেন্ট ও ভবিষ্যৎ বেতন প্রজেকশন ===')
df[['নাম','মূল_বেতন','বার্ষিক_ইনক্রিমেন্ট','পরবর্তী_বছর_বেতন','৩_বছর_পরের_বেতন']]

=== বার্ষিক ইনক্রিমেন্ট ও ভবিষ্যৎ বেতন প্রজেকশন ===

,নাম,মূল_বেতন,বার্ষিক_ইনক্রিমেন্ট,পরবর্তী_বছর_বেতন,৩_বছর_পরের_বেতন
0,মো. আবদুল করিম,78000,3900,81900,90295
1,রহিমা বেগম,56500,2825,59325,65406
2,জাহিদ হোসেন,43000,2150,45150,49778
3,সালমা খাতুন,43000,2150,45150,49778
4,কামাল উদ্দিন,35500,1775,37275,41096
5,নাসরিন আক্তার,35500,1775,37275,41096
6,রফিকুল ইসলাম,29000,1450,30450,33571
7,ফারজানা ইসলাম,35500,1775,37275,41096
8,মোমেনা বেগম,8250,412,8662,9550
9,আবুল হাসেম,8250,412,8662,9550
10,শিরিন আক্তার,11000,550,11550,12734
11,মোস্তফা কামাল,16000,800,16800,18522
12,রেহানা পারভীন,11000,550,11550,12734
13,আনিসুর রহমান,11000,550,11550,12734
14,তাহমিনা বেগম,8250,412,8662,9550

---
## ধাপ ১০ — Merge (দুটো DataFrame জোড়া লাগানো)

In [18]:
# দ্বিতীয় DataFrame: প্রশিক্ষণ তথ্য
প্রশিক্ষণ_data = {
    'আইডি':          ['UZ-001','UZ-002','UZ-003','UZ-004','UZ-005',
                      'UZ-006','UZ-007','UZ-008'],
    'প্রশিক্ষণ':      ['e-Governance','Land Management','Python & AI','DGHS Training',
                      'Modern Agriculture','Education Policy','IBAS++','FP Training'],
    'প্রশিক্ষণ_ভাতা': [5000, 4000, 6000, 4500, 3500, 3500, 3000, 3500]
}
df_প্রশিক্ষণ = pd.DataFrame(প্রশিক্ষণ_data)

# Left merge: সব কর্মকর্তা থাকবে, প্রশিক্ষণ না থাকলে NaN
df_merge = pd.merge(df, df_প্রশিক্ষণ, on='আইডি', how='left')

# NaN এর জায়গায় ০
df_merge['প্রশিক্ষণ_ভাতা'] = df_merge['প্রশিক্ষণ_ভাতা'].fillna(0).astype(int)
df_merge['প্রশিক্ষণ']     = df_merge['প্রশিক্ষণ'].fillna('নেই')

# সর্বমোট বেতন = মোট বেতন + প্রশিক্ষণ ভাতা
df_merge['সর্বমোট_বেতন'] = df_merge['মোট_বেতন'] + df_merge['প্রশিক্ষণ_ভাতা']

print('=== Merge এর পরে ডেটা ===')
df_merge[['নাম','মোট_বেতন','প্রশিক্ষণ','প্রশিক্ষণ_ভাতা','সর্বমোট_বেতন']]

=== Merge এর পরে ডেটা ===

               নাম  মোট_বেতন           প্রশিক্ষণ  প্রশিক্ষণ_ভাতা  সর্বমোট_বেতন
0   মো. আবদুল করিম    114600        e-Governance            5000        119600
1       রহিমা বেগম     83425     Land Management            4000         87425
2      জাহিদ হোসেন     63850         Python & AI            6000         69850
3      সালমা খাতুন     63850       DGHS Training            4500         68350
4     কামাল উদ্দিন     52975  Modern Agriculture            3500         56475
5    নাসরিন আক্তার     52975    Education Policy            3500         56475
6     রফিকুল ইসলাম     43550              IBAS++            3000         46550
7    ফারজানা ইসলাম     52975         FP Training            3500         56475
8      মোমেনা বেগম     13462                 নেই               0         13462
9       আবুল হাসেম     13462                 নেই               0         13462
10    শিরিন আক্তার     17450                 নেই               0         17450
11   মোস্তফা কামাল     24700                 নেই               0         24700
12   রেহানা পারভীন     17450                 নেই               0         17450
13    আনিসুর রহমান     17450                 নেই               0         17450
14    তাহমিনা বেগম     13462                 নেই               0         13462

---
## ধাপ ১১ — String Operations (নাম ও পদবি নিয়ে কাজ)

In [19]:
# নামে 'বেগম' আছে এমন কর্মকর্তা
বেগম_ফিল্টার = df[df['নাম'].str.contains('বেগম')]
print(f"'বেগম' আছে এমন কর্মকর্তা: {len(বেগম_ফিল্টার)} জন")
print(বেগম_ফিল্টার[['নাম','পদবি']].to_string())

# পদবিতে 'Officer' আছে
officer_filter = df[df['পদবি'].str.contains('Officer')]
print(f"\n'Officer' পদবি: {len(officer_filter)} জন")

# নামের প্রথম অংশ বের করা
df['প্রথম_নাম'] = df['নাম'].str.split().str[-1]  # শেষ শব্দ
print('\nশেষ নামের তালিকা:')
print(df['প্রথম_নাম'].values)

'বেগম' আছে এমন কর্মকর্তা: 3 জন
             নাম     পদবি
1     রহিমা বেগম  AC Land
8    মোমেনা বেগম     MLSS
14  তাহমিনা বেগম  Sweeper

'Officer' পদবি: 6 জন

শেষ নামের তালিকা:
['করিম' 'বেগম' 'হোসেন' 'খাতুন' 'উদ্দিন' 'আক্তার' 'ইসলাম' 'ইসলাম' 'বেগম'
 'হাসেম' 'আক্তার' 'কামাল' 'পারভীন' 'রহমান' 'বেগম']

---
## ধাপ ১২ — Date Operations (তারিখ নিয়ে কাজ)

In [20]:
# তারিখ থেকে বিভিন্ন তথ্য বের করা
df['যোগদান_বছর']  = df['যোগদান_তারিখ'].dt.year
df['যোগদান_মাস']  = df['যোগদান_তারিখ'].dt.month

print('=== বছর অনুযায়ী নিয়োগ ===')
print(df.groupby('যোগদান_বছর')['নাম'].count().rename('নিয়োগ_সংখ্যা'))

print('\n=== ২০১৫ সালের পরে যোগদান করেছেন ===')
নতুন = df[df['যোগদান_বছর'] > 2015]
নতুন[['নাম','পদবি','যোগদান_তারিখ','চাকরির_বছর']]

=== বছর অনুযায়ী নিয়োগ ===
যোগদান_বছর
2003    1
2004    1
2006    1
2009    1
2011    1
2012    1
2013    1
2014    1
2015    1
2016    1
2017    2
2018    1
2019    1
2020    1
Name: নিয়োগ_সংখ্যা, dtype: int64

=== ২০১৫ সালের পরে যোগদান করেছেন ===

              নাম                     পদবি যোগদান_তারিখ  চাকরির_বছর
2     জাহিদ হোসেন              ICT Officer   2017-08-20         7.4
4    কামাল উদ্দিন      Agriculture Officer   2018-04-05         6.7
5   নাসরিন আক্তার        Education Officer   2016-07-22         8.5
7   ফারজানা ইসলাম  Family Planning Officer   2017-09-14         7.3
10   শিরিন আক্তার         Office Assistant   2019-10-11         5.2
12  রেহানা পারভীন            Sub Assistant   2020-06-15         4.6

---
## ধাপ ১৩ — চূড়ান্ত রিপোর্ট ও Excel Export

In [21]:
# চূড়ান্ত বেতন বিবরণী DataFrame
চূড়ান্ত_রিপোর্ট = df[[
    'আইডি','নাম','পদবি','বিভাগ','গ্রেড','লিঙ্গ',
    'যোগদান_তারিখ','চাকরির_বছর',
    'মূল_বেতন','বাড়িভাড়া','চিকিৎসা_ভাতা','মোট_বেতন',
    'বার্ষিক_ইনক্রিমেন্ট','পরবর্তী_বছর_বেতন'
]].copy()

# সারসংক্ষেপ সারি যোগ
সারসংক্ষেপ = pd.DataFrame([{
    'আইডি': '---',
    'নাম': 'সর্বমোট',
    'মূল_বেতন':           চূড়ান্ত_রিপোর্ট['মূল_বেতন'].sum(),
    'বাড়িভাড়া':           চূড়ান্ত_রিপোর্ট['বাড়িভাড়া'].sum(),
    'চিকিৎসা_ভাতা':       চূড়ান্ত_রিপোর্ট['চিকিৎসা_ভাতা'].sum(),
    'মোট_বেতন':           চূড়ান্ত_রিপোর্ট['মোট_বেতন'].sum(),
    'বার্ষিক_ইনক্রিমেন্ট': চূড়ান্ত_রিপোর্ট['বার্ষিক_ইনক্রিমেন্ট'].sum(),
    'পরবর্তী_বছর_বেতন':   চূড়ান্ত_রিপোর্ট['পরবর্তী_বছর_বেতন'].sum(),
}])

চূড়ান্ত_রিপোর্ট = pd.concat([চূড়ান্ত_রিপোর্ট, সারসংক্ষেপ], ignore_index=True)
print('=== চূড়ান্ত বেতন বিবরণী ===')
চূড়ান্ত_রিপোর্ট

=== চূড়ান্ত বেতন বিবরণী ===

,আইডি,নাম,পদবি,বিভাগ,গ্রেড,লিঙ্গ,যোগদান_তারিখ,চাকরির_বছর,মূল_বেতন,বাড়িভাড়া,চিকিৎসা_ভাতা,মোট_বেতন,বার্ষিক_ইনক্রিমেন্ট,পরবর্তী_বছর_বেতন
0,UZ-001,মো. আবদুল করিম,UNO,প্রশাসন,3.0,পুরুষ,2009-03-15,15.8,78000,35100,1500,114600,3900,81900
1,UZ-002,রহিমা বেগম,AC Land,রাজস্ব,6.0,মহিলা,2014-06-01,10.6,56500,25425,1500,83425,2825,59325
2,UZ-003,জাহিদ হোসেন,ICT Officer,ICT,9.0,পুরুষ,2017-08-20,7.4,43000,19350,1500,63850,2150,45150
3,UZ-004,সালমা খাতুন,Health Officer,স্বাস্থ্য,9.0,মহিলা,2015-11-10,9.2,43000,19350,1500,63850,2150,45150
4,UZ-005,কামাল উদ্দিন,Agriculture Officer,কৃষি,10.0,পুরুষ,2018-04-05,6.7,35500,15975,1500,52975,1775,37275
5,UZ-006,নাসরিন আক্তার,Education Officer,শিক্ষা,10.0,মহিলা,2016-07-22,8.5,35500,15975,1500,52975,1775,37275
6,UZ-007,রফিকুল ইসলাম,Accounts Officer,অর্থ,11.0,পুরুষ,2012-01-30,12.9,29000,13050,1500,43550,1450,30450
7,UZ-008,ফারজানা ইসলাম,Family Planning Officer,স্বাস্থ্য,10.0,মহিলা,2017-09-14,7.3,35500,15975,1500,52975,1775,37275
8,UZ-009,মোমেনা বেগম,MLSS,প্রশাসন,20.0,মহিলা,2004-02-18,20.9,8250,3712,1500,13462,412,8662
9,UZ-010,আবুল হাসেম,MLSS,প্রশাসন,20.0,পুরুষ,2006-05-25,18.6,8250,3712,1500,13462,412,8662
10,UZ-011,শিরিন আক্তার,Office Assistant,প্রশাসন,16.0,মহিলা,2019-10-11,5.2,11000,4950,1500,17450,550,11550
11,UZ-012,মোস্তফা কামাল,Sub Assistant Engineer,প্রকৌশল,14.0,পুরুষ,2013-03-08,11.8,16000,7200,1500,24700,800,16800
12,UZ-013,রেহানা পারভীন,Sub Assistant,ICT,16.0,মহিলা,2020-06-15,4.6,11000,4950,1500,17450,550,11550
13,UZ-014,আনিসুর রহমান,Driver,প্রশাসন,16.0,পুরুষ,2011-12-01,13.1,11000,4950,1500,17450,550,11550
14,UZ-015,তাহমিনা বেগম,Sweeper,প্রশাসন,20.0,মহিলা,2003-09-27,21.3,8250,3712,1500,13462,412,8662
15,---,সর্বমোট,NaN,NaN,NaN,NaN,NaT,NaN,429750,193386,22500,645636,21486,451236

In [22]:
# Excel-এ export — একাধিক sheet-এ
try:
    with pd.ExcelWriter('উপজেলা_বেতন_রিপোর্ট.xlsx', engine='openpyxl') as writer:

        # Sheet 1: সম্পূর্ণ বিবরণী
        চূড়ান্ত_রিপোর্ট.to_excel(writer, sheet_name='বেতন বিবরণী', index=False)

        # Sheet 2: বিভাগভিত্তিক সারসংক্ষেপ
        বিভাগ_বিশ্লেষণ.to_excel(writer, sheet_name='বিভাগভিত্তিক')

        # Sheet 3: Pivot Table
        pivot.to_excel(writer, sheet_name='Pivot Table')

        # Sheet 4: ভবিষ্যৎ প্রজেকশন
        df[['নাম','মূল_বেতন','পরবর্তী_বছর_বেতন','৩_বছর_পরের_বেতন']].to_excel(
            writer, sheet_name='বেতন প্রজেকশন', index=False
        )

    print('✓ উপজেলা_বেতন_রিপোর্ট.xlsx সফলভাবে তৈরি হয়েছে!')
    print('  Sheet সমূহ: বেতন বিবরণী, বিভাগভিত্তিক, Pivot Table, বেতন প্রজেকশন')
except ImportError:
    print('openpyxl নেই। চালাও: pip install openpyxl')
    df.to_csv('উপজেলা_বেতন_রিপোর্ট.csv', index=False, encoding='utf-8-sig')
    print('✓ CSV হিসেবে সংরক্ষিত হয়েছে।')

✓ উপজেলা_বেতন_রিপোর্ট.xlsx সফলভাবে তৈরি হয়েছে!
  Sheet সমূহ: বেতন বিবরণী, বিভাগভিত্তিক, Pivot Table, বেতন প্রজেকশন

---
## ধাপ ১৪ — Text-based ভিজুয়ালাইজেশন (Matplotlib ছাড়া)

In [23]:
print('=' * 60)
print('       উপজেলা বেতন বিশ্লেষণ — সারসংক্ষেপ ড্যাশবোর্ড')
print('=' * 60)

মোট = df['মোট_বেতন'].sum()
print(f'\n  মোট কর্মকর্তা-কর্মচারী : {len(df):>5} জন')
print(f'  মাসিক মোট বেতন বিল     : ৳{মোট:>10,.0f}')
print(f'  বার্ষিক মোট বেতন বিল   : ৳{মোট*12:>10,.0f}')
print(f'  গড় মোট বেতন            : ৳{df["মোট_বেতন"].mean():>10,.0f}')

print('\n--- বিভাগভিত্তিক বেতন বিল (বার চার্ট) ---')
বিভাগ_মোট = df.groupby('বিভাগ')['মোট_বেতন'].sum().sort_values(ascending=False)
সর্বোচ্চ = বিভাগ_মোট.max()
for বিভাগ, মোট_ব in বিভাগ_মোট.items():
    বার_দৈর্ঘ্য = int((মোট_ব / সর্বোচ্চ) * 30)
    print(f'  {বিভাগ:<12} {"█" * বার_দৈর্ঘ্য} ৳{মোট_ব:,.0f}')

print('\n--- বেতন স্তর বিতরণ ---')
স্তর_গণনা = df['বেতন_স্তর'].value_counts()
for স্তর, গণনা in স্তর_গণনা.items():
    বার = '●' * গণনা
    print(f'  {str(স্তর)[:30]:<32} {বার} ({গণনা} জন)')

print('\n--- লিঙ্গভিত্তিক তথ্য ---')
for লিঙ্গ, গ্রুপ in df.groupby('লিঙ্গ'):
    print(f'  {লিঙ্গ}: {len(গ্রুপ)} জন, গড় বেতন ৳{গ্রুপ["মূল_বেতন"].mean():,.0f}')

print('\n' + '=' * 60)
print(f'  সর্বোচ্চ বেতনধারী: {df.loc[df["মূল_বেতন"].idxmax(), "নাম"]} (৳{df["মূল_বেতন"].max():,})')
print(f'  সর্বনিম্ন বেতনধারী: {df.loc[df["মূল_বেতন"].idxmin(), "নাম"]} (৳{df["মূল_বেতন"].min():,})')
print('=' * 60)

============================================================
       উপজেলা বেতন বিশ্লেষণ — সারসংক্ষেপ ড্যাশবোর্ড
============================================================

  মোট কর্মকর্তা-কর্মচারী :    15 জন
  মাসিক মোট বেতন বিল     : ৳   645,636
  বার্ষিক মোট বেতন বিল   : ৳ 7,747,632
  গড় মোট বেতন            : ৳    43,042

--- বিভাগভিত্তিক বেতন বিল (বার চার্ট) ---
  প্রশাসন      ██████████████████████████████ ৳189,886
  স্বাস্থ্য    ██████████████████ ৳116,825
  রাজস্ব       █████████████ ৳83,425
  ICT          ████████████ ৳81,300
  কৃষি         ████████ ৳52,975
  শিক্ষা       ████████ ৳52,975
  অর্থ         ██████ ৳43,550
  প্রকৌশল      ███ ৳24,700

--- বেতন স্তর বিতরণ ---
  নিম্ন (১৫ হাজারের নিচে)          ●●●●●● (6 জন)
  উচ্চ-মধ্যম (৩০-৫০ হাজার)         ●●●●● (5 জন)
  মধ্যম (১৫-৩০ হাজার)              ●● (2 জন)
  উচ্চ (৫০ হাজারের উপরে)           ●● (2 জন)

--- লিঙ্গভিত্তিক তথ্য ---
  পুরুষ: 7 জন, গড় বেতন ৳31,536
  মহিলা: 8 জন, গড় বেতন ৳26,125

============================================================
  সর্বোচ্চ বেতনধারী: মো. আবদুল করিম (৳78,000)
  সর্বনিম্ন বেতনধারী: মোমেনা বেগম (৳8,250)
============================================================

---
## অনুশীলন — নিজে করো

**সহজ:**
1. শুধু `প্রশাসন` বিভাগের কর্মকর্তাদের DataFrame filter করো।
2. `চাকরির_বছর` অনুযায়ী sort করে প্রথম ৫ জন বের করো।

**মাঝারি:**
3. `groupby('শিক্ষাগত_যোগ্যতা')` দিয়ে শিক্ষাগত যোগ্যতা অনুযায়ী গড় বেতন বের করো।
4. ৫ বছর পরের বেতন প্রজেকশন column যোগ করো (`৫_বছর_পরের_বেতন`)।

**কঠিন:**
5. প্রতিটি বিভাগ থেকে সর্বোচ্চ বেতনধারী কর্মকর্তার নাম বের করো।

```python
# ইঙ্গিত ৫ নম্বরের জন্য:
সর্বোচ্চ_idx = df.groupby('বিভাগ')['মূল_বেতন'].idxmax()
df.loc[সর্বোচ্চ_idx, ['বিভাগ','নাম','মূল_বেতন']]
```